/*
Title: PowderDrumProtocol.h
Purpose:
- Interface to the autogenerated protocol definition.
- Provides parameter metadata lookup and validation helpers.
- Hides storage implementation (PROGMEM) from application code.
*/

#pragma once

#include <Arduino.h>
#include "protocol_generated.h"

namespace PowderDrumProtocol
{
    // Find parameter metadata.
    bool findParameter(uint8_t parameterID, ParamMeta& metadata);

    // Check if parameter exists.
    bool exists(uint8_t parameterID);

    // Check access permissions.
    bool isReadable(uint8_t parameterID);
    bool isWritable(uint8_t parameterID);

    //Return parameter type.
    ParamType type(uint8_t parameterID);
}