/*
Title: SerialManager.h
Author: Matthew Smith 22173112
Date: 29/07/26

Purpose:
- Generic serial communications handler.
- Implements the packet framing protocol defined in protocol_generated.h.
- Performs packet reception, validation and dispatch.
- Uses the autogenerated protocol metadata for parameter validation.
- Exposes a simple callback interface for application GET/SET handling.

The protocol definition (message IDs, parameter IDs, access permissions,
protocol version, etc.) is generated automatically from the protocol JSON
and should never be duplicated here.
*/

#pragma once

#include <Arduino.h>
#include "protocol_generated.h"

///////////////////////
// Callback Typedefs //
///////////////////////

using SetCallback = void (*)(uint8_t parameterID, float value);
using GetCallback = float (*)(uint8_t parameterID);

//////////////////////////
// Float Serialization //
//////////////////////////

union FloatBytes
{
    float f;
    uint8_t b[4];
};

//////////////////////////////
// Packet Representation //
//////////////////////////////

struct Packet
{
    uint8_t version;
    uint8_t msgID;
    uint8_t direction;
    uint8_t length;
    uint8_t payload[MAX_PAYLOAD_BYTES];
    uint8_t crc;
};

///////////////////////////
// Serial State Machine //
///////////////////////////

enum class SerialState : uint8_t
{
    IDLE,
    READ_HEADER,
    READ_PAYLOAD,
    VALIDATE,
    DISPATCH
};

/////////////////////
// Serial Handler //
/////////////////////

class SerialManager
{
public:

    ///////////////////
    // Public API //
    ///////////////////

    void begin(uint32_t baudRate);
    void update();

    ///////////////////////
    // Outgoing Messages //
    ///////////////////////

    void sendParameter(uint8_t parameterID, float value);
    void sendStatus(uint8_t statusCode);
    void sendHeartbeat();

    //////////////////
    // Callbacks //
    //////////////////

    void onSet(SetCallback callback);
    void onGet(GetCallback callback);

private:

    /////////////////////////
    // State Machine //
    /////////////////////////

    void _handleIdle();
    void _handleReadHeader();
    void _handleReadPayload();
    void _handleValidate();
    void _handleDispatch();

    /////////////////////////
    // Command Handlers //
    /////////////////////////

    void _onCmdSet(const Packet& packet);
    void _onCmdGet(const Packet& packet);

    ///////////////////////
    // Packet TX //
    ///////////////////////

    void _sendPacket(uint8_t msgID, uint8_t direction, const uint8_t* payload, uint8_t length);
    void _sendACK(uint8_t acknowledgedMessage);
    void _sendNACK(uint8_t rejectedMessage, NackError error);

    //////////////////
    // CRC //
    //////////////////

    uint8_t _computeCRC(const uint8_t* data, uint8_t length);

    //////////////////////////
    // Internal State //
    //////////////////////////

    SerialState _state = SerialState::IDLE;
    Packet _rxPacket {};
    uint8_t _rxBuffer[HEADER_SIZE_BYTES + MAX_PAYLOAD_BYTES + 1] {};
    uint8_t _bytesRead = 0;
    uint32_t _lastByteTime = 0;

    ////////////////////////
    // Application Hooks //
    ////////////////////////

    SetCallback _setCallback = nullptr;
    GetCallback _getCallback = nullptr;
};